const {test}=require('node:test');const assert=require('node:assert/strict');
process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='test';process.env.GROQ_API_KEY='test';
const {ManualOrderService}=require('../dist/orders/manual-order.service');
const valid=()=>({customer_name:'Cliente Fictício',customer_phone:'+351912345678',delivery_type:'PICKUP',payment_method:'MULTIBANCO',items:[{product:'Dom Tradicional',quantity:1}]});
function service(){const s=new ManualOrderService();s.settings={get:async()=>({delivery_fee:null,payment_methods:['DINHEIRO','MULTIBANCO']})};s.orders.products={findByName:async name=>[{id:1,name:'Dom Tradicional',price:8.99},{id:2,name:'Menu Dom Tradicional',price:12.49},{id:3,name:'Açaí 350 ml',price:8.99}].find(p=>p.name===name)};s.orders.repository={createOrder:async()=>{throw Error('Preview must never save')}};return s;}
test('manual preview ignores caller prices/totals and recalculates from catalog',async()=>{const input={...valid(),total:0.01,items:[{product:'Dom Tradicional',quantity:2,price:0.01,subtotal:0.02}]};const p=await service().preview(input);assert.equal(p.total,17.98);assert.equal(p.items[0].price,8.99);assert.equal(p.amount_paid,null);assert.equal(p.address,null);});
test('cash delivery uses exact change and keeps notes in kitchen-readable components',async()=>{const input={...valid(),delivery_type:'DELIVERY',address:'Morada fictícia',payment_method:'DINHEIRO',amount_paid:20,items:[{product:'Dom Tradicional',quantity:1,notes:'Sem cebola'}]};const p=await service().preview(input);assert.equal(p.change,11.01);assert.deepEqual(p.items[0].components,['Observação: Sem cebola']);assert.equal(p.address,'Morada fictícia');});
test('configured delivery fee is added by the server only for delivery',async()=>{const s=service();s.settings={get:async()=>({delivery_fee:2.5,payment_methods:['MULTIBANCO']})};const delivery=await s.preview({...valid(),delivery_type:'DELIVERY',address:'Morada fictícia'});assert.equal(delivery.delivery_fee,2.5);assert.equal(delivery.total,11.49);const pickup=await s.preview(valid());assert.equal(pickup.delivery_fee,0);assert.equal(pickup.total,8.99);});
test('menu must select drink and acai must explicitly select toppings',async()=>{const s=service();await assert.rejects(s.preview({...valid(),items:[{product:'Menu Dom Tradicional',quantity:1}]}),/Coca-Cola/);assert.equal((await s.preview({...valid(),items:[{product:'Menu Dom Tradicional',quantity:1,drink:'Zero'}]})).total,12.49);await assert.rejects(s.preview({...valid(),items:[{product:'Açaí 350 ml',quantity:1}]}),/toppings/);assert.deepEqual((await s.preview({...valid(),items:[{product:'Açaí 350 ml',quantity:1,toppings:[]}]})).items[0].toppings,[]);});
test('invalid order inputs cannot reach a preview or a write',async()=>{for(const patch of [{customer_name:''},{customer_phone:'abc'},{delivery_type:'OTHER'},{delivery_type:'DELIVERY',address:''},{payment_method:'PIX'},{delivery_fee:5},{items:[]},{items:[{product:'Dom Tradicional',quantity:0}]},{items:[{product:'missing',quantity:1}]},{payment_method:'DINHEIRO',amount_paid:5},{payment_method:'DINHEIRO',amount_paid:NaN},{payment_method:'DINHEIRO',amount_paid:20.001}])await assert.rejects(service().preview({...valid(),...patch}));});
