const {test}=require('node:test');const assert=require('node:assert/strict');const {normalizeMetaMessages}=require('../dist/whatsapp/meta-messages');
const expected={accountId:'100',phoneNumberId:'200'};
const msg=(id='wamid.test',body='Olá')=>({id,from:'351900000000',timestamp:'1788418800',type:'text',text:{body}});
const envelope=(messages,extra={})=>({object:'whatsapp_business_account',entry:[{id:'100',changes:[{field:'messages',value:{messaging_product:'whatsapp',metadata:{phone_number_id:'200'},messages,...extra}}]}]});
test('processes every message in batch and separates delivery receipts',()=>{const result=normalizeMetaMessages(envelope([msg(),msg('wamid.2','quero batata')],{statuses:[{id:'outgoing',status:'delivered',timestamp:'1788418801'}]}),expected);assert.equal(result.messages.length,2);assert.equal(result.messages[1].text,'quero batata');assert.deepEqual(result.statuses,[{id:'outgoing',status:'delivered',timestamp:'1788418801'}]);});
test('identity is stable across envelopes, duplicates collapse, conflicting IDs fail closed',()=>{const one=normalizeMetaMessages(envelope([msg(),msg()]),expected);assert.equal(one.messages.length,1);assert.equal(one.messages[0].key,normalizeMetaMessages(envelope([msg()]),expected).messages[0].key);assert.throws(()=>normalizeMetaMessages(envelope([msg(),msg('wamid.test','different')]),expected),/conflitante/);});
test('another account or destination phone cannot reach the conversation processor',()=>{const foreign=envelope([msg()]);foreign.entry[0].id='999';assert.equal(normalizeMetaMessages(foreign,expected).messages.length,0);foreign.entry[0].id='100';foreign.entry[0].changes[0].value.metadata.phone_number_id='999';assert.equal(normalizeMetaMessages(foreign,expected).messages.length,0);assert.throws(()=>normalizeMetaMessages(envelope([]),{accountId:'',phoneNumberId:''}));});
test('media is classified unsupported, never promoted to a text order',()=>{const result=normalizeMetaMessages(envelope([{...msg(),type:'image',image:{id:'media-id',caption:'confirmar'}}]),expected);assert.equal(result.messages[0].processable,false);assert.equal(result.messages[0].text,undefined);});
test('malformed messages reject the envelope and timestamps remain source data',()=>{for(const patch of [{id:null},{from:'not-phone'},{timestamp:'yesterday'},{text:{body:''}},{text:{body:'x'.repeat(4097)}}])assert.throws(()=>normalizeMetaMessages(envelope([{...msg(),...patch}]),expected));assert.equal(normalizeMetaMessages(envelope([msg()]),expected).messages[0].timestamp,'1788418800');});
