import {useEffect,useState} from "react";import {api} from "../services/api";import {useAuth} from "../context/AuthContext";import "../styles/settings.css";
type SettingsData={restaurant_name:string;phone:string|null;address:string|null;opening_hours:string|null;delivery_fee:number|null;pix_key:string|null;payment_methods:string[];ai_greeting:string|null;ai_unknown_reply:string|null;ai_personality:string|null};
const empty:SettingsData={restaurant_name:"Dom Hamburgueria",phone:null,address:null,opening_hours:null,delivery_fee:null,pix_key:null,payment_methods:["DINHEIRO","MULTIBANCO"],ai_greeting:null,ai_unknown_reply:null,ai_personality:null};
export default function Settings(){const {profile}=useAuth();const [form,setForm]=useState(empty);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const editable=profile?.role==="ADMIN";
 useEffect(()=>{let active=true;api.get('/settings').then(({data})=>{if(active)setForm({...empty,...data});}).catch(()=>{if(active)setMessage('Não foi possível carregar as configurações.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[]);
 const field=(key:keyof SettingsData,value:any)=>setForm(current=>({...current,[key]:value}));
 async function save(e:React.FormEvent){e.preventDefault();if(!editable||busy)return;setBusy(true);setMessage('');try{const payload={...form,delivery_fee:form.delivery_fee===null?null:Number(form.delivery_fee)};const {data}=await api.put('/settings',payload);setForm({...empty,...data});setMessage('Configurações guardadas.');}catch(error:any){setMessage(error.response?.data?.message||'Não foi possível guardar as configurações.');}finally{setBusy(false);}}
 if(loading)return <p role="status">Carregando configurações…</p>;
 return <section className="settings-page"><h1>Configurações da loja</h1><p>{editable?'Edite os dados usados pelo atendimento e pela operação.':'Consulte os dados definidos pelo administrador.'}</p><form onSubmit={save}><fieldset disabled={!editable||busy}><legend>Dados da hamburgueria</legend><label>Nome<input required maxLength={150} value={form.restaurant_name} onChange={e=>field('restaurant_name',e.target.value)}/></label><label>Telefone<input maxLength={20} value={form.phone||''} onChange={e=>field('phone',e.target.value||null)}/></label><label>Morada<textarea maxLength={500} value={form.address||''} onChange={e=>field('address',e.target.value||null)}/></label><label>Horário<textarea maxLength={1000} placeholder="Não configurado" value={form.opening_hours||''} onChange={e=>field('opening_hours',e.target.value||null)}/></label></fieldset>
 <fieldset disabled={!editable||busy}><legend>Entrega e pagamento</legend><label>Taxa de entrega (€)<input type="number" min="0" max="1000" step="0.01" placeholder="Não configurada" value={form.delivery_fee??''} onChange={e=>field('delivery_fee',e.target.value===''?null:Number(e.target.value))}/></label><p>PIX permanece indisponível até a integração de pagamento ser configurada.</p><label>Chave PIX<input disabled maxLength={200} value={form.pix_key||''}/></label><label className="setting-check"><input type="checkbox" checked={form.payment_methods.includes('DINHEIRO')} onChange={e=>field('payment_methods',e.target.checked?[...form.payment_methods,'DINHEIRO']:form.payment_methods.filter(x=>x!=='DINHEIRO'))}/>Dinheiro</label><label className="setting-check"><input type="checkbox" checked={form.payment_methods.includes('MULTIBANCO')} onChange={e=>field('payment_methods',e.target.checked?[...form.payment_methods,'MULTIBANCO']:form.payment_methods.filter(x=>x!=='MULTIBANCO'))}/>Multibanco</label></fieldset>
 <fieldset disabled={!editable||busy}><legend>Atendimento da IA</legend><label>Saudação<textarea maxLength={500} placeholder="Usar mensagem padrão" value={form.ai_greeting||''} onChange={e=>field('ai_greeting',e.target.value||null)}/></label><label>Mensagem quando não entender<textarea maxLength={500} placeholder="Usar mensagem padrão" value={form.ai_unknown_reply||''} onChange={e=>field('ai_unknown_reply',e.target.value||null)}/></label><label>Personalidade<textarea maxLength={1000} placeholder="Acolhedora, próxima, profissional, simpática e objetiva." value={form.ai_personality||''} onChange={e=>field('ai_personality',e.target.value||null)}/></label></fieldset>{message&&<p role="status">{message}</p>}{editable&&<button disabled={busy}>{busy?'Guardando…':'Guardar configurações'}</button>}</form></section>}
